routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


//Route::resource('rest', 'RestTestController')->names('RestTest');

Route::group(['namespace' => 'Blog', 'prefix' => 'blog'], function(){
Route::resource('posts', 'PostController')->names('blog.posts');
});

//Admin panel
$groupData = [
    'namespace' => 'Blog\Admin',
    'prefix' =>'admin/blog',
];

Route::group($groupData , function(){
    //blogcategory
    $methods = ['index','edit','store','update','create',];
    Route::resource('categories', 'CategoryController')
    ->only($methods)
    ->names('blog.admin.categories');
});

app/Http/Controllers/Blog/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Blog\Admin;

use Illuminate\Http\Request;
use App\Http\Requests\BlogCategoryUpdateRequest;
use App\Http\Requests\BlogCategoryCreateRequest;
use App\Http\Controllers\Blog\Controller;
use App\Models\BlogCtegory as BlogCategory;

class CategoryController extends BaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //dd(__METHOD__);
        $dsd = BlogCategory::all();
        $paginator = BlogCategory::paginate(5);
        return View('Blog.admin.categories.index', compact('paginator'));
       // dd($dsd);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
       // dd(__METHOD__);
       $item = new BlogCategory();
      // dd($item);
       $categoryList = BlogCategory::all();
       
       return view('Blog.admin.categories.edit', compact('item', 'categoryList'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(BlogCategoryCreateRequest $request)
    {
               $request->flash();
       // $id = 111111;
        $data = $request->input();
        if(empty($data['slug']))
        {
            $data['slug'] = str_slug($data['title']);
        }
        //дописать
        $item = new BlogCategory($data);
        dd($item);
        $item->save();
        
        if($item)
        {
            return redirect()
                ->route('blog.admin.categories.edit', $item->id)
                ->with(['success' => 'Успешно сохранено']);
        } else{
           return back()//редирект назад
                ->withErrors(['msg' =>'Ошибка сохранения'])
                ->withInputs();
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        dd(__METHOD__);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        //dd(__METHOD__);
        $item = BlogCategory::findOrFail($id);
        $categoryList = BlogCategory::all();
        
        return View('Blog.admin.categories.edit', compact('item', 'categoryList'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(BlogCategoryUpdateRequest $request, $id)
    {
        //валидацию тут нежелательно, лучше в реквестах
       /* $rules = [
            'title' => 'required|min:5|max:200',
            'slug'  => 'max:200',
            'description' => 'string|max:500|min:3',
            'parent_id'  => 'required|integer|exists:blog_ctegories,id',
        ];
      //  $validatedData = $this->validate($request, $rules);
       // $validatedData = $request->validate($rules);
       // dd($validatedData);
      /* $validator = \Validator::make($request->all(),$rules);
       $validatedData[] = $validator->passes();
     //   $validatedData[] = $validator->validate();
         $validatedData[] = $validator->valid();
          $validatedData[] = $validator->failed();
           $validatedData[] = $validator->errors();
            $validatedData[] = $validator->fails();
        //
        dd($validatedData);*/
        //dd(__METHOD__, $request->all(), $id);
        $request->flash();
       // $id = 111111;
        $item = BlogCategory::find($id);
        if(empty($item))
        {
            return back()
                ->withErrors("Запись id=[{$id}] не найдена")
               ->withInputs($request->all());
            //dd($id);
        }
        
        $data = $request->all();
        $result = $item->fill($data)->save();
        
        if($result)
        {
            return redirect()
                ->route('blog.admin.categories.edit', $item->id)
                ->with(['success' => 'Успешно сохранено']);
        } else{
           return back()//редирект назад
                ->withErrors('Ошибка сохранения')
                ->withInputs();
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        dd(__METHOD__);
    }
}

resources/views/Blog/admin/categories/edit.blade.php
@extends('layouts.app')

@section('content')
    @php
        /** \App\Models\BlogCtegory*/
    @endphp
    @if($item->exists)
    <form method="POST" action="{{ route('blog.admin.categories.update', $item->id)}}">
    {{ method_field('PATCH') }}
    @else
        <form method="POST" action="{{ route('blog.admin.categories.store', $item->id)}}">
   @endif 
        {{csrf_field()}}
        <div class="container">
            @php
                /** @var \Illuminate\Support\ViewErrorBag $errors */ 
            @endphp
            @if($errors->any())
                <div class="row justify-content-center">
                    <div class="col-md-11">
                        <div class="alert alert-danger" role="alert">
                            <button type="button" class="close" data-dissmiss="alert" aria-label="Close">
                                <span aria-hidden="true"></span>                            
                            </button>
                            {{$errors->first()}}
                        </div>
                    </div>
                </div>
            @endif
            @if(session('success'))
                  <div class="row justify-content-center">
                    <div class="col-md-11">
                        <div class="alert alert-success" role="alert">
                            <button type="button" class="close" data-dissmiss="alert" aria-label="Close">
                                <span aria-hidden="true"></span>                            
                            </button>
                            {{ session('success')}}
                        </div>
                    </div>
                </div>
            @endif
        <div class="row justify-content-center">
                <div class="col-md-8">
                    @include('Blog.admin.categories.includes.item_edit_main_col')
                </div>
                 <div class="col-md-3">
                    @include('Blog.admin.categories.includes.item_edit_add_col')
                </div>
                
            </div>
        </div>
    </form>
@endsection

resources/views/Blog/admin/categories/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class = "row justify-content-center">
        <div class="col-md-12">
            <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
                <a class="btn btn-primary" href="{{route('blog.admin.categories.create')}}">Добавить</a>
            </nav>
            <div class="card">
                <div class="card-body">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Категория</th>
                                <th>Родитель</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($paginator as $item)
                                @php /** @var \App\Models\BlogCategory $item */ @endphp
                                <tr>
                                    <td>{{$item->id}}</td>
                                    <td>
                                        <a href="{{route('blog.admin.categories.edit',$item->id )}}">
                                            {{$item->title}}
                                        </a>
                                    </td>
                                    <td @if(in_array($item->parent_id, [0,1])) style="color:#ccc" @endif>
                                        {{$item->parent_id}}{{--$item->parentCategory->title --}}

                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
         </div>
    </div>
    @if($paginator->total() > $paginator->count())
        <br>
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        {{$paginator->links()}}
                    </div>
                </div>
            </div>
        </div>
</div>
@endif
@endsection